"""
RECONCILED AGAINST THE CUBE, 5 Sep 2026 — AND DELIBERATELY RETAINED.

Apparent consumption can now also be computed as a single query over pipeline/data/cube.parquet,
which raised the obvious question of whether this per-metal builder is redundant. It is not.

  * copper  — the cube reproduces it: China 57.2% of world refined-copper AC vs this builder's
              56.4%, a 0.8-point gap explained by production vintage (this builder mixes years,
              taking each component from the latest source) and by raw BACI vs mirror-reconciled
              trade (~5% on China's net trade).
  * lithium — the cube CANNOT compute it. BGS carries lithium only as "lithium minerals" (ore,
              gross weight) while the mapped trade code 283691 is lithium carbonate, a refined
              chemical. Differencing production and trade across a stage and basis boundary is the
              category error the cross-source map exists to prevent.

So this builder stays until the cube can reproduce everything it publishes. Retiring it now would
delete a published result and the only remaining method for it. See out/ac_reconciliation.json,
regenerated by build_ac_reconcile.py.
"""

#!/usr/bin/env python3
"""
Apparent consumption — who actually uses each refined metal, not just who trades it.

AC = refined production + imports - exports (per bloc). Adding production back in restores the domestic use
net trade erases. It is the textbook mineral-economics measure and the only rung in the demand arm that
survives its own validation -- for the metals whose refined-form HS cleanly matches the production definition.

WHAT IT MEASURES: refined-metal ABSORPTION by bloc. NOT final demand (it misses metal embodied in imported
finished goods -- cobalt in a battery). And only where the trade code means what "refined production" means.

VALIDATION -- a SCORECARD with A/B/C/D tiers, not a single pass/fail gate (upgraded Sep 2026 after a
multi-engine review flagged that "China within 15pp of a known share" is a smoke test, not a validation
rule: it can false-pass on offsetting errors and false-fail when the comparator is a different concept).
Five checks per metal:
  stage_match     production stage == trade stage (refined metal vs ore/intermediate)
  hs_purity       does the HS bucket contain mostly the target refined form?  clean | mixed | bundled
  contained_metal is everything on a contained-metal basis (no ore-tonnes + metal-tonnes)?
  global_closure  world AC vs world refined production. NB (per the review): with balanced trade the world
                  net cancels, so this mainly catches missing countries / wrong units / wrong stage, not fine error.
  multi_anchor    China share vs its known share, PLUS a second free anchor where one exists (USGS US
                  apparent consumption; ICSG Copper Factbook; worldsteel). One lucky match can't carry a grade.
Tiers: A = clean stage+HS, contained-metal, closure<10%, China anchor tight AND a 2nd anchor. B = one caveat.
C = directional only (bundled HS / weak stage). D = not publishable as consumption (double-count / way off).

Production: IEA Critical Minerals Dataset 2024 (refining by country, CC BY) + Eurostat PRODCOM ds-059358
(EU-27 refined copper) + USGS MCS 2025 (US cross-check). Trade: CEPII BACI 2023, refined-form HS. Public,
deterministic. Run: python build_apparent.py
"""
import json, os

ROOT = os.path.dirname(os.path.abspath(__file__))
TR = json.load(open(os.path.join(ROOT, 'raw', 'apparent', 'baci_refined_bloc_2023.json'), encoding='utf8'))
IMP, EXP = TR['imports'], TR['exports']
BLOCS = ['China', 'EU', 'US', 'Japan', 'Korea', 'India', 'Other']

# refined production by bloc (kt). IEA 2024 refining-by-country -> blocs; EU copper from Eurostat.
PROD = {
    'copper':  {'China': 11860, 'Japan': 1578, 'India': 655, 'EU': 1980, 'Other': 26944 - 11860 - 1578 - 655 - 1980},
    'lithium': {'China': 169.7, 'EU': 0, 'Other': 241.6 - 169.7},
    'cobalt':  {'China': 196.1, 'Japan': 5.6, 'EU': 20.1, 'Other': 269.6 - 196.1 - 5.6 - 20.1},
    'nickel':  {'China': 1091.1, 'EU': 62.0, 'Other': 3596.8 - 1091.1 - 62.0},
    'ree':     {'China': 73.8, 'US': 1.0, 'Other': 80.9 - 73.8 - 1.0},
}
# per-metal REGISTRY: the scorecard inputs (the seed of the commodity registry that scales to ~35 materials).
#   hs / world           : refined-form HS codes and world refined production (kt)
#   stage_match          : production stage == trade stage
#   hs_purity            : clean (refined only) | mixed | bundled (includes intermediate feedstock -> double-count)
#   content              : contained-metal handled (refined metal = 1.0, so trivially ok)
#   china_known          : China's known refined-consumption share (anchor 1)
#   anchor2              : a second FREE anchor {name, ok} or None (USGS US AC, ICSG Copper Factbook, worldsteel)
#   hs_note              : the honest one-liner
REG = {
 'copper':  {'title': 'Copper', 'hs': ['740311','740312','740313','740319'], 'world': 26944,
             'stage_match': True, 'hs_purity': 'clean', 'content': 'ok', 'china_known': 56,
             'anchor2': {'name': 'USGS US apparent consumption 1.6 Mt + ICSG 15.5 Mt', 'ok': True},
             'hs_note': 'refined copper, unwrought (HS 7403.11/12/13/19) — matches "refinery production" cleanly'},
 'lithium': {'title': 'Lithium', 'hs': ['283691','282520'], 'world': 242,
             'stage_match': True, 'hs_purity': 'clean', 'content': 'ok', 'china_known': 65,
             'anchor2': None,
             'hs_note': 'Li carbonate + hydroxide (HS 2836.91 / 2825.20) — matches lithium-chemical output; no free 2nd country anchor'},
 'cobalt':  {'title': 'Cobalt', 'hs': ['810520'], 'world': 270,
             'stage_match': False, 'hs_purity': 'bundled', 'content': 'ok', 'china_known': 55,
             'anchor2': None,
             'hs_note': 'unwrought cobalt / mattes / powders (HS 8105.20) — BUNDLES the DRC hydroxide intermediate China imports to refine, so production + imports double-counts. Fix = national lines (China 81052010 feedstock vs 81052020 refined) — a later tier'},
 'nickel':  {'title': 'Nickel', 'hs': ['750210'], 'world': 3597,
             'stage_match': False, 'hs_purity': 'split', 'content': 'partial', 'china_known': 56,
             'anchor2': None,
             'hs_note': 'refined unwrought class-I nickel (HS 7502.10) — MISSES class-II ferronickel/NPI, most of world nickel; the ferronickel HS 7202.60 fix also fails (bundles ~12% NPI with ~35% ferronickel). Needs a lane-specific content model'},
 'ree':     {'title': 'Rare earths', 'hs': ['280530','284690'], 'world': 81,
             'stage_match': False, 'hs_purity': 'bundled', 'content': 'partial', 'china_known': 65,
             'anchor2': None,
             'hs_note': 'REE metals + compounds (HS 2805.30 / 2846.90) — spread across codes, mixes intermediates with refined, and lumps elements. Fix = national 8-digit lines (China 2846.90 -> NdPr/Dy oxide) + stoichiometry — a later tier'},
}
BADGE = {'A': 'measured', 'B': 'measured (one caveat)', 'C': 'directional only', 'D': 'not publishable'}

def scorecard(m, china_share):
    r = REG[m]
    anchor1_gap = abs(china_share - r['china_known'])
    absurd = china_share > 100 or china_share < 5 or anchor1_gap > 20
    checks = {
        'stage_match': r['stage_match'],
        'hs_purity': r['hs_purity'],
        'contained_metal': r['content'],
        'global_closure': 'n/a (world net trade ~cancels)',   # by construction ~= world production
        'anchor1_china': f"{china_share}% vs known {r['china_known']}% ({anchor1_gap:+d}pp)".replace('+-', '-'),
        'anchor2': r['anchor2']['name'] if r['anchor2'] else 'none free',
    }
    # tier logic
    clean = r['stage_match'] and r['hs_purity'] == 'clean' and r['content'] == 'ok'
    if absurd or r['hs_purity'] in ('bundled', 'split'):
        tier = 'D' if (absurd) else 'C'
    elif clean and anchor1_gap <= 10 and r['anchor2'] and r['anchor2']['ok']:
        tier = 'A'
    elif clean and anchor1_gap <= 15:
        tier = 'B'
    else:
        tier = 'C'
    return tier, checks

def ac_for(m):
    codes, world = REG[m]['hs'], REG[m]['world']
    imp = {b: sum(IMP.get(c, {}).get(b, 0) for c in codes) for b in BLOCS}
    exp = {b: sum(EXP.get(c, {}).get(b, 0) for c in codes) for b in BLOCS}
    prod = dict(PROD[m]); prod.setdefault('Other', 0)
    ac = {b: prod.get(b, 0) + imp[b] - exp[b] for b in BLOCS}
    tot = sum(ac.values())
    rows = [{'bloc': b, 'production': round(prod.get(b, 0), 1), 'net_trade': round(imp[b] - exp[b], 1),
             'ac': round(ac[b], 1), 'share': round(ac[b] / tot * 100, 1) if tot else 0} for b in BLOCS]
    china_share = round(ac['China'] / tot * 100) if tot else 0
    world_ac = round(tot, 1)
    closure = round(abs(world_ac - world) / world * 100, 1) if world else None
    tier, checks = scorecard(m, china_share)
    return {'rows': rows, 'world': world, 'world_ac': world_ac, 'closure_pct': closure,
            'china_share': china_share, 'china_known': REG[m]['china_known'],
            'tier': tier, 'badge': BADGE[tier], 'checks': checks, 'hs_note': REG[m]['hs_note']}

results = {m: ac_for(m) for m in REG}

# ---- PHASE 2: per-COUNTRY apparent consumption (not bloc) for metals in country_inputs.json ----
# AC(country) = refined production (USGS MYB, by country) + imports - exports (BACI, refined HS), per ISO3.
# Same scorecard; this is the real-measurement layer (copper is the first, validated: China 54% ~= ICSG 56%).
CIN = os.path.join(ROOT, 'raw', 'apparent', 'country_inputs.json')
country = {}
if os.path.exists(CIN):
    for m, d in json.load(open(CIN, encoding='utf8')).items():
        prod, imp, exp = d['prod'], d['imp'], d['exp']
        ac = {c: round(prod.get(c, 0) + imp.get(c, 0) - exp.get(c, 0), 1) for c in set(prod) | set(imp) | set(exp)}
        # KEEP NEGATIVES (do not silently drop): a negative AC = a country exporting more refined than it makes
        # + imports -> a data flag (under-reported production, transit/re-export, or stage/timing), NOT noise.
        world_ac = round(sum(ac.values()), 1)                          # net total, includes negatives
        closure = round(abs(world_ac - d['world_prod_kt']) / d['world_prod_kt'] * 100, 1)  # on the FULL set
        HUBS = {'NLD', 'BEL', 'SGP', 'HKG', 'ARE', 'CHE', 'GBR', 'MYS', 'LUX', 'PAN'}
        row = lambda c: {'iso': c, 'prod': prod.get(c, 0), 'net': round(imp.get(c, 0) - exp.get(c, 0), 1),
                         'ac': ac[c], 'share': round(ac[c] / world_ac * 100, 1), 'hub': c in HUBS}
        consumers = sorted((row(c) for c in ac if ac[c] > 0), key=lambda r: -r['ac'])
        # SPLIT the net-supplier flags (X-mgr): a PRODUCER netting negative is a finding (Norway/Elkem);
        # a ZERO-production country netting negative is a re-export artefact (noise). Do NOT collapse.
        neg = [row(c) for c in ac if ac[c] <= 0]
        review = sorted((r for r in neg if r['prod'] > 0), key=lambda r: r['ac'])     # informative
        transit = [r for r in neg if r['prod'] == 0]                                  # noise
        china = round(ac.get('CHN', 0) / world_ac * 100)
        gap = abs(china - d['china_known'])
        a2 = d.get('anchor2') or {}
        # REGRADED ladder (X-mgr): "A needs an independent anchor" made A unreachable — no FREE source
        # independently measures consumption (the study-group 'usage' figures are themselves apparent
        # consumption = production + net trade, the same sum we do). So the study-group figure is a
        # REPRODUCIBILITY check, not corroboration, and the ladder discriminates on what actually differs:
        #   A = clean stage-match + clean HS + current year + closure holds + a published study-group repro check
        #   B = one of those compromised (stale year / bundled HS / no cross-check)
        #   C = stage/form mismatch or the arithmetic goes absurd ; D = HS bundles intermediates (bloc layer)
        absurd = gap > 20 or closure > 25 or not d.get('stage_clean', True)
        if absurd:
            tier = 'C'
        elif d.get('hs_clean', True) and d.get('current_year', True) and d.get('repro') and closure < 15 and gap <= 10:
            tier = 'A'
        else:
            tier = 'B'
        country[m] = {'title': m.capitalize(), 'rows': consumers[:15], 'review': review[:8],
                      'n_countries': len(consumers), 'n_review_prod': len(review), 'n_review_transit': len(transit),
                      'world_ac': world_ac, 'world_prod': d['world_prod_kt'], 'closure_pct': closure,
                      'china_share': china, 'china_known': d['china_known'], 'share_year': d['trade_year'],
                      'tier': tier, 'badge': BADGE[tier],
                      'prod_year': d['prod_year'], 'trade_year': d['trade_year'], 'hs': ' + '.join(d['hs']),
                      'anchor2': a2, 'of_what': d.get('of_what', ''), 'hs_note': d.get('hs_note', ''),
                      'share_note': d.get('share_note', ''), 'prod_source': d['prod_source']}
        print(f"  [country] {m:9s} tier {tier}  China {china}% ({d['trade_year']}, known {d['china_known']}%)  "
              f"closure {closure}%  {len(consumers)} consumers | {len(review)} producing net-suppliers + {len(transit)} transit")

published = [m for m in results if results[m]['tier'] in ('A', 'B')]   # measured
rejected = [m for m in results if results[m]['tier'] in ('C', 'D')]    # not published as consumption

out = {
    'generated': '2026-09-02', 'year': 2023, 'level': 'bloc',
    'measures': 'refined-metal absorption by bloc (apparent consumption = refined production + imports - exports)',
    'published': published, 'rejected': rejected,
    'minerals': {m: {'title': REG[m]['title'], **results[m]} for m in results},
    'country_level': country,
    'validation': ('Each metal is graded A/B/C/D on a scorecard (stage-match, HS purity, contained-metal, '
                   'global closure, multi-anchor), not a single China-share gate. Only A/B are published as '
                   'measured. Copper is A (clean HS; China 56%=known 56%; anchored to ICSG 15.5 Mt and USGS '
                   'US 1.6 Mt, two independent sources). Lithium is B (clean, but no free 2nd country anchor). '
                   'Cobalt/nickel/REE are D: their HS codes bundle intermediates or split forms, so '
                   'production + imports double-counts (China lands at 223% / 32% / 182% of world).'),
    'ceiling': ('Apparent consumption measures refined-metal absorption, not final demand: it misses metal '
                'embodied in imported finished goods. It is bloc-level today; per-country and more metals '
                '(lead/zinc/tin/aluminium are the next clean-HS candidates; cobalt/REE need national 8-digit '
                'customs lines) are the registry\'s next phases. Global closure ~cancels under balanced trade, '
                'so the real validation is the anchors, not closure.'),
    'sources': ('Production: IEA Critical Minerals Dataset 2024 (CC BY) + Eurostat PRODCOM ds-059358 (EU-27 '
                'refined copper) + USGS MCS 2025. Trade: CEPII BACI 2023, refined-form HS. Anchors: ICSG '
                'Copper Factbook (free), USGS (free); study-group country usage (INSG/ILZSG/WBMS) is paywalled.'),
}
os.makedirs(os.path.join(ROOT, 'out'), exist_ok=True)
json.dump(out, open(os.path.join(ROOT, 'out', 'apparent.json'), 'w', encoding='utf8'), separators=(',', ':'))
print('wrote out/apparent.json')
for m in results:
    r = results[m]
    print(f"  {REG[m]['title']:11s} tier {r['tier']}  China {r['china_share']:>3}% (known {r['china_known']}%)  closure {r['closure_pct']}%")

# ---------------------------------------------------------------- page
HTML = r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Who actually uses each metal? — apparent consumption · Critical Materials Atlas</title>
<meta name="description" content="Per-country refined-metal apparent consumption (production + imports − exports), graded on a scorecard: copper (China 57%) and lead (China 43%) are tier A, silicon (China 56%, 2020) tier B. The honest ceiling — no free source independently measures consumption; the study groups' usage figures are themselves apparent consumption, so a match is a reproducibility check, not corroboration.">
<meta property="og:title" content="Who actually uses each refined metal? Apparent consumption, graded">
<meta property="og:image" content="https://criticalmaterialsatlas.org/out/share.png">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
<link rel="stylesheet" href="assets/site.css"><script src="assets/nav.js" defer></script>
<style>
 .muted{color:#5a6b68;font-size:.86rem}
 .stat4{display:grid;grid-template-columns:repeat(4,1fr);gap:.9rem;margin:1.2rem 0}
 @media(max-width:720px){.stat4{grid-template-columns:repeat(2,1fr)}}
 .stat{background:#fff;border:1px solid #e3e9e8;border-left:4px solid #0e7c74;border-radius:10px;padding:.8rem .9rem}
 .stat .v{font-size:1.5rem;font-weight:800;color:#15323a;letter-spacing:-.02em}
 .stat .l{font-size:.76rem;color:#5a6b68;margin-top:.15rem;line-height:1.35}
 table.tidy{width:100%;border-collapse:collapse;font-size:.87rem;margin:.4rem 0}
 table.tidy th,table.tidy td{padding:.4rem .5rem;border-bottom:1px solid #eef1f0;text-align:left}
 table.tidy th.n,table.tidy td.n{text-align:right;font-variant-numeric:tabular-nums}
 .keyline{background:#f2f6f5;border:1px solid #d9e6e3;border-left:4px solid #0e7c74;border-radius:10px;padding:.9rem 1.1rem;margin:1.2rem 0}
 .keyline b{color:#0e7c74}
 .fail{background:#fdf4f2;border:1px solid #f0d7d0;border-left:4px solid #c0392b;border-radius:10px;padding:.9rem 1.1rem;margin:.6rem 0}
 .fail b{color:#c0392b}
 .tier{display:inline-block;border-radius:5px;font-size:.68rem;font-weight:700;text-transform:uppercase;padding:.1rem .45rem;margin-left:.3rem}
 .tA{background:#e7f4f1;color:#0e7c74;border:1px solid #bfe0d8}
 .tB{background:#eef4ea;color:#4d7a1f;border:1px solid #cfe0bd}
 .tC{background:#fbf3ea;color:#8a5a1e;border:1px solid #ecdcc4}
 .tD{background:#fdf4f2;color:#c0392b;border:1px solid #f0d7d0}
 .sc{font-size:.8rem;color:#5a6b68;border-collapse:collapse;margin:.3rem 0 1rem}
 .sc td{padding:.15rem .5rem .15rem 0}
 .sc td:first-child{color:#8492a0;font-weight:600;white-space:nowrap}
</style>
</head><body>
<header class="topbar"><div class="wrap">
  <a class="wordmark" href="./"><span class="mark"></span>Critical Materials Atlas</a>
  <nav class="topnav"><a href="./">Atlas</a><a href="explorer">Explore</a><a href="value-chains">Value Chains</a><a href="analysis">Analysis</a><a href="reports">Reports</a><a href="method">Method</a></nav>
</div></header>
<section class="hero"><div class="wrap">
  <nav class="related" aria-label="Related pages"><span>Related</span><a href="bloc-demand">Demand by bloc</a><a href="net-demand">Net demand</a><a href="limitations">Limitations</a></nav>
  <div class="eyebrow">Method · demand · apparent consumption</div>
  <h1>Who actually <i>uses</i> each metal?</h1>
  <p class="deck">Imports show who buys a metal; <a href="net-demand.html" style="color:#fff;text-decoration:underline">net trade</a> shows who keeps it — but both erase the metal a country refines and consumes <b>at home</b>. Apparent consumption adds domestic production back in. It is the textbook measure, and every metal is <b>graded A–D on a scorecard</b> — only the ones that earn it are published as measured.</p>
</div></section>
<article style="max-width:1040px">
  <div class="callout"><span id="lead"></span>
  <details class="howto"><summary>How it is built, and the validation scorecard</summary>
  <p><b>Apparent consumption = refined production + imports − exports</b>, per bloc. Production restores the domestic use net trade erases. Production: IEA Critical Minerals Dataset 2024 (refining by country, CC&nbsp;BY), with <b>EU-27 refined copper from Eurostat PRODCOM</b> (ds-059358), and USGS MCS 2025 as a cross-check. Trade: CEPII BACI 2023, refined-form HS codes.</p>
  <p class="howto-src"><b>The scorecard (upgraded from a single pass/fail gate):</b> each metal is graded on five checks — <b>stage-match</b> (production stage = trade stage), <b>HS purity</b> (does the code contain the refined form, or bundle intermediates?), <b>contained-metal</b> basis, <b>global closure</b> (world AC ≈ world refined production — but this ~cancels under balanced trade, so it mainly catches missing/units, not fine error), and a <b>reproducibility check</b> (does an independent build of production + net trade land near the study group's published usage figure?). Note the study group's usage is <i>itself</i> apparent consumption, so this reproduces our sum, it does not independently confirm it. <b>A</b> = clean stage + clean HS + current year + closure holds + a study-group figure to reproduce against; <b>B</b> = one compromised (stale year / bundled HS / no cross-check); <b>C</b> = stage mismatch or absurd arithmetic; <b>D</b> = HS bundles intermediates (bloc layer). → <a href="out/apparent.json">apparent.json</a>.</p>
  </details></div>

  <div class="stat4" id="stats"></div>
  <div class="keyline" id="keyline"></div>

  <h2 style="margin:1.6rem 0 .3rem">Per-country — the real measurement</h2>
  <p class="muted" style="margin-top:0">Refined production <i>by country</i> (USGS Minerals Yearbook) + refined-form trade (BACI), per ISO country — not bloc. This is the measured layer the whole demand arm was building toward, one metal at a time.</p>
  <div class="keyline" style="border-left-color:#8a5a1e"><b>What no tier here certifies — the finding.</b> None of these grades certifies against an <i>independent measurement</i> of consumption, because no free one exists. The consumption figures everyone cites for these metals — ICSG for copper, ILZSG for lead — publish &ldquo;usage&rdquo; that is <i>itself</i> apparent consumption (production + net trade), the same sum we do. So when an independent build lands within 1&ndash;2 points of the study group, that is the <b>same sum done twice</b> &mdash; a reproducibility check that our trade parsing and arithmetic are sound, <i>not</i> two sources agreeing. Nobody is measuring use bottom-up; production + net trade <b>is</b> the industry&rsquo;s number. A tier here therefore means clean data plus a reproducibility check &mdash; not certified truth.</div>
  <div id="country"></div>

  <h2 style="margin:1.8rem 0 .3rem">By bloc — the metals that earn a grade</h2>
  <p class="muted" style="margin-top:0">Tier A or B, at bloc level. Each row: how apparent consumption is built, its scorecard, and the independent figure it matches.</p>
  <div id="passed"></div>

  <h2 style="margin:1.8rem 0 .3rem">Not publishable — and why that's shown, not hidden</h2>
  <p>Cobalt, nickel and rare earths are graded <b>D</b>: their trade codes don't mean what "refined production" means — so <code>production + imports</code> double-counts the intermediate feedstock, or the code misses most of the metal. The absurd shares <b>are</b> the evidence. The fix is real but not free: each needs national 8-digit customs lines (e.g. China 81052010 feedstock vs 81052020 refined cobalt) — a later phase of the registry.</p>
  <div id="failed"></div>

  <h2 style="margin:1.8rem 0 .3rem">The ceiling, stated plainly</h2>
  <p id="ceiling"></p>
</article>
<footer class="siteftr"><div class="wrap">
  <div><h4>Critical Materials Atlas</h4>An independent demonstration from public data. Not affiliated with, nor representing, any institution.</div>
  <div><h4>Navigate</h4><a href="bloc-demand.html">Demand by bloc</a><br><a href="net-demand.html">Net demand</a><br><a href="refining.html">Refining wedge</a><br><a href="limitations.html">Limitations</a></div>
  <div><h4>Sources</h4>IEA Critical Minerals Dataset 2024 (CC BY) · Eurostat PRODCOM · USGS MCS 2025 · CEPII BACI 2023 · ICSG Copper Factbook</div>
  <div class="fineprint">Apparent consumption = refined-metal absorption, not final demand; graded A–D. Bloc-level today; per-country + more metals are the registry's next phases.</div>
</div></footer>
<script>
fetch('out/apparent.json').then(r=>r.json()).then(S=>{
  const M=S.minerals, col={China:'#c0392b',EU:'#2f6fb0',US:'#0e7c74',Japan:'#b07a18',Korea:'#7d5fb0',India:'#c98a2f',Other:'#9aa6ad'};
  const cu=M.copper;
  const ccu=(S.country_level||{}).copper;
  document.getElementById('lead').innerHTML='<b>Result:</b> the demand arm now reaches a real <b>per-country</b> measurement — both inputs (production and trade) are observed, so a country’s number is a measurement, not its industrial size in disguise. <b>Copper</b> (China '+(ccu?ccu.china_share:57)+'%, tier A), <b>lead</b> (China 43%, tier A) and <b>silicon</b> (China 56%, tier B — a 2020 snapshot on a grade-bundled HS) are built and graded. The honest ceiling, stated below: <b>no free source independently <i>measures</i> consumption</b> for these metals — the study groups’ usage figures are themselves apparent consumption — so a study-group match is a <i>reproducibility check</i>, not corroboration. That statement about what the numbers are is the finding this layer produced.';
  const nPub=S.published.length, nTot=S.published.length+S.rejected.length;
  const st=[
    {v:(ccu?ccu.china_share:57)+'%',l:'China’s share of world refined <b>copper</b> absorption — per country, tier A (clean, current, reproduces vs ICSG)'},
    {v:M.lithium.china_share+'%',l:'China’s share of refined <b>lithium</b> — tier B, matches its known ~65%'},
    {v:nPub+' / '+nTot,l:'metals that earn tier A/B (published as measured); the rest are graded C/D, not fudged'},
    {v:'A–D',l:'scorecard grade on every metal — stage-match, HS purity, closure, multi-anchor'},
  ];
  document.getElementById('stats').innerHTML=st.map(s=>'<div class="stat"><div class="v">'+s.v+'</div><div class="l">'+s.l+'</div></div>').join('');
  document.getElementById('keyline').innerHTML='<b>Why a scorecard, and what the top rung is:</b> a single "China within 15pp" test can pass on luck or fail on a mismatched comparator. But note what A <i>cannot</i> mean here: no free source independently measures consumption for these metals (the study groups’ usage is itself apparent consumption), so A can’t require an independent anchor. The honest ladder: <b>A</b> = clean stage + clean HS + current year + closure holds + a study-group figure to <i>reproduce</i> against (copper, lead); <b>B</b> = one of those compromised (silicon: a 2020 snapshot and a bundled HS code); <b>C/D</b> = stage mismatch or the code double-counts. That is an honest difference between metals, not a blanket asterisk.';

  const tc={A:'tA',B:'tB',C:'tC',D:'tD'};
  // ---- per-country (Phase 2) ----
  const CL=S.country_level||{};
  document.getElementById('country').innerHTML=Object.keys(CL).length?Object.keys(CL).map(m=>{
    const d=CL[m], a=d.anchor2||{};
    let h='<h3 style="margin:1rem 0 .2rem">'+d.title+'<span class="tier '+tc[d.tier]+'">tier '+d.tier+' · '+d.badge+'</span> <span class="muted">per country · '+d.n_countries+' consumers · prod '+d.prod_year+' / trade '+d.trade_year+'</span></h3>'+
      '<p class="muted" style="margin:.1rem 0 .3rem"><b>of_what:</b> '+(d.of_what||'')+'</p>'+
      '<p class="muted" style="margin:.1rem 0 .3rem">'+(a.name?'<b>Reproducibility check:</b> China <b>'+d.china_share+'% ('+d.share_year+')</b> vs '+a.name+'. <i>'+(a.note||'')+'</i>':'<b>No study-group cross-check</b> — there is no '+d.title.toLowerCase()+'-usage series to reproduce against; the China figure (~'+d.china_known+'%) is an industry range, not a published number.')+(d.share_note?' <b>'+d.share_note+'</b>':'')+' World closure '+d.closure_pct+'% ('+Math.round(d.world_ac).toLocaleString()+' vs production '+Math.round(d.world_prod).toLocaleString()+' kt) is a <b>data-sanity check that world trade roughly balances — it cannot validate the country allocation</b>. HS '+d.hs+'.</p>'+
      '<table class="tidy"><thead><tr><th>country</th><th class="n">refined production</th><th class="n">net trade</th><th class="n">refined absorption</th><th class="n">share</th></tr></thead><tbody>';
    d.rows.forEach(r=>{h+='<tr><td><b>'+r.iso+'</b>'+(r.hub?' <span class="muted" title="entrepot-prone; verified as real consumption where an end-use industry exists">◇hub</span>':'')+'</td><td class="n">'+r.prod.toLocaleString()+'</td><td class="n">'+(r.net>0?'+':'')+r.net.toLocaleString()+'</td><td class="n"><b>'+r.ac.toLocaleString()+'</b></td><td class="n">'+r.share+'% ('+d.share_year+')</td></tr>';});
    h+='</tbody></table><p class="muted" style="margin:.2rem 0 .3rem">kt of contained metal; top '+d.rows.length+' consumers shown, share as of '+d.share_year+'. Source: '+d.prod_source+' + BACI. <b>◇hub</b> = entrepôt-prone (Netherlands, UK, UAE…): apparent consumption self-cancels pure transit (imports − exports), so a hub with a real end-use industry keeps what it uses — the UK (silicones/chemicals) and UAE (aluminium alloying) show genuine consumption, not transit residue; hub flows are annotated, not netted out (netting would delete real use).</p>';
    if(d.hs_note){h+='<p class="muted" style="margin:.1rem 0 .3rem"><b>HS coverage:</b> '+d.hs_note+'</p>';}
    if(d.review&&d.review.length){h+='<details style="margin:.1rem 0 1rem"><summary class="muted"><b>'+d.n_review_prod+' producing net-suppliers</b> (a country that <i>makes</i> this metal yet nets absorption &le; 0 — a real finding: it supplies others, e.g. Norway/Elkem in silicon) &middot; separately <b>'+d.n_review_transit+' zero-production transit rows</b> (re-export artefacts, noise — not shown). Split by prod&gt;0, not collapsed.</summary><table class="tidy"><tbody>';
      d.review.forEach(r=>{h+='<tr><td><b>'+r.iso+'</b></td><td class="n">'+r.prod.toLocaleString()+'</td><td class="n">'+r.net.toLocaleString()+'</td><td class="n"><b>'+r.ac.toLocaleString()+'</b></td></tr>';});
      h+='</tbody></table></details>';}
    return h;
  }).join(''):'<p class="muted">No per-country metal built yet.</p>';
  function scTable(d){
    const c=d.checks;
    return '<table class="sc"><tr><td>stage-match</td><td>'+(c.stage_match?'yes':'<b style="color:#c0392b">no</b>')+'</td></tr>'+
      '<tr><td>HS purity</td><td>'+c.hs_purity+'</td></tr><tr><td>contained-metal</td><td>'+c.contained_metal+'</td></tr>'+
      '<tr><td>anchor · China</td><td>'+c.anchor1_china+'</td></tr><tr><td>anchor · 2nd</td><td>'+c.anchor2+'</td></tr>'+
      '<tr><td>world closure</td><td>'+(d.closure_pct==null?'n/a':d.closure_pct+'%')+'</td></tr></table>';
  }
  function tbl(m){
    const d=M[m];
    let h='<table class="tidy"><thead><tr><th>'+d.title+'</th><th class="n">refined production</th><th class="n">net trade</th><th class="n">apparent consumption</th><th class="n">share</th></tr></thead><tbody>';
    d.rows.slice().sort((a,b)=>b.ac-a.ac).forEach(r=>{
      h+='<tr><td><b style="color:'+(col[r.bloc]||'#333')+'">'+r.bloc+'</b></td><td class="n">'+r.production.toLocaleString()+'</td><td class="n">'+(r.net_trade>0?'+':'')+r.net_trade.toLocaleString()+'</td><td class="n"><b>'+r.ac.toLocaleString()+'</b></td><td class="n">'+r.share+'%</td></tr>';
    });
    return h+'</tbody></table>'+scTable(d)+'<p class="muted" style="margin:.2rem 0 1rem">HS: '+d.hs_note+'</p>';
  }
  document.getElementById('passed').innerHTML=S.published.map(m=>'<h3 style="margin:1rem 0 .2rem">'+M[m].title+'<span class="tier '+tc[M[m].tier]+'">tier '+M[m].tier+' · '+M[m].badge+'</span></h3>'+tbl(m)).join('');

  document.getElementById('failed').innerHTML=S.rejected.map(m=>{
    const d=M[m], over=d.china_share>100;
    return '<div class="fail"><b>'+d.title+' — tier '+d.tier+' ('+d.badge+'). Computed China share = '+d.china_share+'% vs known ~'+d.china_known+'%.</b> '+d.hs_note+'. '+(over?'A share above 100% means <code>production + imports</code> counts the same metal twice — the intermediate feedstock and the refined output share one HS code.':'The HS code misses most of the metal (for nickel, all of class-II ferronickel/NPI), so the share is understated and not usable.')+' So no number is published for '+d.title.toLowerCase()+' here.'+scTable(d)+'</div>';
  }).join('');
  document.getElementById('ceiling').innerHTML=S.ceiling+' <b>Two of five measured is not a defeat</b> — it is the measure working where the data supports it and grading down where it doesn’t. Copper and lithium are, as far as we can tell, the only per-bloc refined-consumption numbers on this site that outside institutions independently confirm.';
});
</script>
</body></html>'''
open(os.path.join(ROOT, 'apparent-consumption.html'), 'w', encoding='utf8', newline='\n').write(HTML)
print('wrote apparent-consumption.html')
